config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "quizzes#new"

  resource :quizzes, only: %i[new create show destroy]
end

app/models/answer.rb
class Answer < ActiveYaml::Base
  set_root_path "app/models/seeds"
  set_filename "answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quiz.rb
class Quiz < ActiveYaml::Base
  set_root_path "app/models/seeds"
  set_filename "quiz"

  # 問題数
  TOTAL_QUESTIONS = 7
  # kaisei フォントの問題
  KAISEI_QUESTIONS = [ 1, 3, 5 ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :reset_quiz, only: %i[new]

  def new
    # セッションに問題数を保存
    session[:quiz_count] ||= 0
    session[:quiz_count] += 1

    # 選択肢を設定
    @choices = get_choices
  end

  def create
    # ユーザーが選んだ選択肢から選択肢番号と選択肢の値に分割
    @choice_number, user_choice = params[:user_choice]&.split("-")
    # 正誤判定
    @is_answer_correct = Answer.find_by(name: user_choice)
    # 正解数をカウント
    session[:correct_count] ||= 0
    session[:correct_count] += 1 if @is_answer_correct
    # 次の問題があるか判定
    @has_next_question = session[:quiz_count] < Quiz::TOTAL_QUESTIONS
  end

  def show
    @answers = Answer.all.map(&:name)
  end

  def destroy
    # セッションを削除
    reset_session
    # トップページに遷移
    redirect_to root_path, status: :see_other
  end

  private

  # 現在の問題数に対応する選択肢をセット
  # 1 -> 1 ~ 4
  # 2 -> 5 ~ 8
  # 3 -> 9 ~ 12
  # 4 -> 13 ~ 16
  # 5 -> 17 ~ 20
  # 6 -> 21 ~ 24
  # 7 -> 25 ~ 28
  def get_choices
    Quiz.where(id: (session[:quiz_count] * 4 - 3)..session[:quiz_count] * 4).map(&:name).shuffle
  end

  # クイズが問題上限に達したらセッションをリセット
  def reset_quiz
    session[:quiz_count] ||= 0
    reset_session if session[:quiz_count] >= Quiz::TOTAL_QUESTIONS
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 正解数に応じてお祝いの言葉を作成
  def generate_congratulations
    case session[:correct_count]
    when 0
      "まだまだこれから！もう一度チャレンジしてみましょう！"
    when 1
      "いいスタートですね！次も頑張ってください！"
    when 2
      "いい調子ですね！さらに進んでいきましょう！"
    when 3
      "順調ですね！この調子でいきましょう！"
    when 4
      "パーフェクトが見えてきましたね！もう少しです！"
    when 5
      "素晴らしいです！パーフェクトまでもうすぐです！"
    when 6
      "あと一歩で満点です！最後のひと踏ん張りです！"
    when 7
      "全ての問題を正解しました！最高のパフォーマンスです！"
    end
  end

  # kaisei フォントを使用するかどうかを判定
  def use_kaisei_font?(num)
    Quiz::KAISEI_QUESTIONS.include?(num)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Twitter リンクカード -->
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="" />
    <meta property="og:url" content=<%= "#{root_url}" %>  />
    <meta property="og:title" content="Jリーグのチーム名を当てるクイズ" />
    <meta property="og:description" content="少し違うチーム名、ファンのあなたなら気づくはず" />
    <meta property="og:image" content="https://i.gyazo.com/7888539a0445471ba604cc2bbfd268ba.png" />
    <!-- Twitter リンクカードここまで -->
    <title>Jリーグのチーム名を当てるクイズ</title>
    <%= favicon_link_tag image_path('favicon.png'), type: 'image/png' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-C0C4EJZ733"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-C0C4EJZ733');
    </script>
    <!-- Google Analytics 終了 -->
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/789a4f769e.js" crossorigin="anonymous"></script>

    <link rel="manifest" href="/manifest.json">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="bg-neutral-content min-h-screen w-full relative pb-20">
      <%= render "shared/header" %>
      <%= yield %>
      <div class="absolute bottom-0 w-full">
        <%= render "shared/footer" %>
      </div>
    </div>
  </body>
</html>

app/views/quizzes/_answers.html.erb
<div class="lg:grid lg:grid-cols-2 gap-4">
<% answers.each_with_index do |answer, idx| %>
  <% if idx == 6 %>
    <div class="mb-8 md:mb-16 col-start-2">
  <% else %>
    <div class="mb-8 md:mb-16">
  <% end %>
    <div class="font-noto text-xl md:text-3xl"><%= "#{idx + 1}問目" %></div>
    <div class=<%= use_kaisei_font?(idx + 1) ? "font-kaisei" : "font-dela" %>>
      <div class="mt-3 md:mt-6 text-2xl md:text-5xl lg:text-4xl 2xl:text-5xl"><%= answer %></div>
    </div>
  </div>
<% end %>
</div>

app/views/quizzes/_correct.html.erb
<div class="flex items-center mb-2 lg:mb-0" id="result">
  <i class="fa-regular fa-circle text-green-500 text-3xl md:text-6xl lg:text-5xl mr-2"></i>
  <div class="font-noto text-xl md:text-4xl lg:text-3xl">正解</div>
</div>

app/views/quizzes/_disable_checked_choice.html.erb
<input type="radio" name=choice class="radio" disabled checked="checked" />

app/views/quizzes/_disable_choices.html.erb
<input type="radio" name=choice class="radio" disabled />

app/views/quizzes/_ending.html.erb
<div class="font-noto">
  <div class="flex mb-6 lg:mb-12 mt-4 md:mt-6 lg:mt-8 2xl:mt-4 justify-center">
    <%= link_to "解答を見る", quizzes_path, data: { turbo_stream: true }, class: "btn md:btn-lg btn-outline btn-success mr-6", id: "answer-button" %>
    <%= link_to "https://twitter.com/intent/tweet?url=#{root_url}&text=#{session[:correct_count]}問正解！！%0a#{generate_congratulations}！%0a%0a%23RUNTEQ祭　%23Jリーグのチーム名を当てるクイズ%0a%0a", :onclick=>"window.open(this.href,'hoge', 'height=480, width=640');return false;", rel: "noopener noreferrer", data: { toggle: "tooltip", placement: "bottom" } do %>
      <button class="btn md:btn-lg btn-outline">X でシェア</button>
    <% end %>
  </div>
  <div class="text-4xl md:text-5xl text-primary animate-text-pop-up-top"><%= "#{session[:correct_count]}問正解！！" %></div>
  <%= link_to "終了する", quizzes_path, data: { turbo_method: :delete }, class: "btn md:btn-lg btn-secondary btn-outline mt-4 lg:mt-6" %>
</div>

app/views/quizzes/_incorrect.html.erb
<div class="flex items-center mb-2 lg:mb-0" id="result">
  <i class="fa-solid fa-xmark text-red-500 text-3xl md:text-6xl lg:text-5xl mr-2"></i>
  <div class="font-noto text-xl md:text-4xl lg:text-3xl">不正解</div>
</div>

app/views/quizzes/_next_button.html.erb
<%= link_to "次の問題へ", root_path, class: "font-noto btn md:btn-lg btn-accent btn-outline lg:ml-3 2xl:ml-6" %>

app/views/quizzes/answer.turbo_stream.erb
<!-- 回答表示ボタンを取り除く -->
<%= turbo_stream.remove "answer-button" %>
<!-- 回答を表示 -->
<%= turbo_stream.replace "quiz_space", partial: "answers", locals: { answers: @answers } %>

app/views/quizzes/check.turbo_stream.erb
<!-- 問題の正解 or 不正解を表示 -->
<% if @is_answer_correct %>
  <%= turbo_stream.replace "submit-button", partial: "correct" %>
<% else %>
  <%= turbo_stream.replace "submit-button", partial: "incorrect" %>
<% end %>

<!-- 「次の問題へ」 or 終了画面を表示 -->
<% if @has_next_question %>
  <%= turbo_stream.after "quiz_space", partial: "quizzes/buttons/next_button" %>
<% else %>
  <%= turbo_stream.after "quiz_space", partial: "ending" %>
  <%= turbo_stream.after "quiz_space", partial: "quizzes/buttons/answer_button" %>
  <%= turbo_stream.after "quiz_space", partial: "quizzes/buttons/x_share_button" %>
<% end %>

<!-- 選択されたラジオボタンを選択不能に更新 -->
<%= turbo_stream.replace "choice-#{@choice_number}", partial: "disable_checked_choice" %>
<!-- 残りのラジオボタンを選択不能に更新 -->
<%= turbo_stream.replace_all ".choice", partial: "disable_choices" %>

app/views/quizzes/create.turbo_stream.erb
<!-- 解答ボタンを非表示 -->
<%= turbo_stream.remove "submit_button" %>
<!-- 問題の正解 or 不正解を表示 -->
<% if @is_answer_correct %>
  <%= turbo_stream.append "answer_space", partial: "correct" %>
<% else %>
  <%= turbo_stream.append "answer_space", partial: "incorrect" %>
<% end %>

<!-- 「次の問題へ」 or 終了画面を表示 -->
<% if @has_next_question %>
  <%= turbo_stream.append "answer_space", partial: "quizzes/next_button" %>
<% else %>
  <%= turbo_stream.after "answer_space", partial: "ending" %>
<% end %>

<!-- 選択されたラジオボタンを選択不能に更新 -->
<%= turbo_stream.replace "choice-#{@choice_number}", partial: "disable_checked_choice" %>
<!-- 残りのラジオボタンを選択不能に更新 -->
<%= turbo_stream.replace_all ".choice", partial: "disable_choices" %>

app/views/quizzes/new.html.erb
<div class="w-5/6 mx-auto max-w-screen-xl text-center mt-16 lg:mt-8 2xl:mt-16">
  <div id="quiz_space">
    <div class="font-noto">
      <div class="text-base md:text-xl 2xl:text-2xl text-neutral my-4 md:my-12 lg:my-2 2xl:my-12">実在するチーム名を選んでね！</div>
      <div class="text-xl md:text-3xl lg:text-2xl 2xl:text-3xl font-semibold my-6 md:my-10 lg:my-4 2xl:my-10"><%= "問題　#{session[:quiz_count]}/#{Quiz::TOTAL_QUESTIONS}" %></div>
    </div>
    <!-- フォントをランダムで生成 -->
    <div class=<%= use_kaisei_font?(session[:quiz_count]) ? "font-kaisei" : "font-dela" %>>
      <%= form_with url: quizzes_path, method: :post, class: "text-2xl md:text-5xl" do |form| %>
        <div id="choices">
          <% @choices.each_with_index do |choice, idx| %>
            <div class="my-8 flex items-center justify-center gap-2">
              <%= form.radio_button :user_choice, "#{idx}-#{choice}", class: "radio choice", id: "choice-#{idx}" %>
              <%= form.label :user_choice, choice, for: "choice-#{idx}" %><br>
            </div>
          <% end %>
        </div>
        <%= form.submit '解答する', id: "submit_button", class: "font-noto btn md:btn-lg btn-accent md:my-6 lg:my-0 2xl:my-6" %>
      <% end %>
    </div>
  </div>
  <div class="flex flex-col lg:flex-row items-center lg:justify-center md:mt-12 lg:mt-3 2xl:mt-8" id="answer_space"></div>
</div>

app/views/quizzes/show.turbo_stream.erb
<!-- 回答表示ボタンを取り除く -->
<%= turbo_stream.remove "answer-button" %>
<!-- 正解不正解を取り除く -->
<%= turbo_stream.remove "result" %>
<!-- 回答を表示 -->
<%= turbo_stream.replace "quiz_space", partial: "answers", locals: { answers: @answers } %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center bg-base-300 text-base-content p-4 flex justify-center">
  Copyright <%= link_to 'すみ', 'https://x.com/sumisumi2000308' %>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-primary-content justify-center">
  <div class="font-bold text-base md:text-2xl">Jリーグのチーム名を当てるクイズ</div>
</div>